get http://localhost:3000/messages
// gets all sent messages
###
get http://localhost:3000/messages?sprint=WD-1.1
// gets all sent messages for a specific sprint
###
get http://localhost:3000/messages?username=@mjansons
// gets all sent messages for a specific user

###
post http://localhost:3000/messages
// sends a message in discord for a specific user
Content-Type: application/json

{
  "username": "mjansons",
  "sprintCode": "WD-1.2"
}

###
get http://localhost:3000/sprints
// gets all sprints

###
post http://localhost:3000/sprints
// adds a new sprint
Content-Type: application/json

{
  "sprintCode": "WD-3.4",
  "title": "A New Sprintrr"
}

###
patch http://localhost:3000/sprints?sprint=WD-2.7
// edits an existing sprint title
Content-Type: application/json

{
  "newTitle": "A New Sprint Titler"
}

###
patch http://localhost:3000/sprints?sprint=WD-2.7
// edits an existing sprintCode
Content-Type: application/json

{
  "newSprintCode": "WD-2.5"
}

###
delete http://localhost:3000/sprints?sprint=WD-2.7
// deletes a sprint


###
get http://localhost:3000/templates
// gets all templates


###
post http://localhost:3000/templates
// adds new template
Content-Type: application/json

{
  "message": "Yay3!"
}

###
patch http://localhost:3000/templates?id=17
// edits an existing sprint title
Content-Type: application/json

{
  "newMessage": "Wowza!"
}

###
delete http://localhost:3000/templates?id=16
// deletes a sprint